name: Release Frontend (ABACUS)

on:
  release:
    types:
      - published
jobs:
  version:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: "${{ github.event.release.tag_name}}"
    outputs:
      CORE_VERSION: "${{ steps.info.outputs.CORE }}"
      DESCRIBE_VERSION: "${{ steps.info.outputs.DESCRIBE }}"
      FULL_VERSION: "${{ steps.info.outputs.FULL }}"
      SHA_TAG: "${{ steps.info.outputs.SHA }}"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: echo -e "$EVENT_CONTEXT\n"
        env:
          EVENT_CONTEXT: ${{ toJson(github.event) }}
      - run: |-
          echo "::set-output name=CORE::${RELEASE_TAG%%-*}"
          echo "::set-output name=FULL::${RELEASE_TAG}"
          echo "::set-output name=SHA::sha-$(git rev-parse --short HEAD)"
          echo "::set-output name=DESCRIBE::$(git describe --tags)"
        id: info

  docker:
    runs-on: ubuntu-latest
    needs:
      - version
    permissions:
      packages: write
      contents: read
    env:
      FULL_VERSION: "${{ needs.version.outputs.FULL_VERSION }}"
      SHA_TAG: "${{ needs.version.outputs.SHA_TAG }}"
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag existing images
        run: >-
          docker buildx imagetools create
          "ghcr.io/opentdf/abacus:${SHA_TAG}"
          --tag "ghcr.io/opentdf/abacus:${FULL_VERSION}"


  helm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs:
      - docker
      - version
    env:
      DESCRIBE_VERSION: "${{ needs.version.outputs.DESCRIBE_VERSION }}"
      FULL_VERSION: "${{ needs.version.outputs.FULL_VERSION }}"
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: yokawasa/action-setup-kube-tools@v0.8.0
        with:
          setup-tools: helm
          helm: "3.9.1"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: push
        run: |
          cd charts
          helm package --app-version "${FULL_VERSION}" --version "${DESCRIBE_VERSION}" abacus
          helm push "abacus-${DESCRIBE_VERSION}.tgz" oci://ghcr.io/${{ github.repository_owner }}/charts
          echo "### Published abacus image [${FULL_VERSION}] and chart [${DESCRIBE_VERSION}]" >> $GITHUB_STEP_SUMMARY
