apiVersion: v1
kind: ConfigMap
metadata:
  name: opentdf-abacus-cm
data:
  ATTRIBUTES_HOST: http://localhost:65432/api/attributes/
  ENTITLEMENTS_HOST: http://localhost:65432/api/entitlements/
  KAS_HOST: http://localhost:65432/api/kas
  KEYCLOAK_CLIENT_ID: dcr-test
  KEYCLOAK_HOST: http://localhost:65432/auth/
  KEYCLOAK_REALM: tdf
  SERVER_BASE_PATH:
