apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "abacus.name" . }}-cm
data:
  KEYCLOAK_HOST: {{ .Values.oidc.serverUrl | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  KEYCLOAK_REALMS: {{ .Values.oidc.queryRealms | quote }}
  ATTRIBUTES_HOST: {{ .Values.attributes.serverUrl | quote }}
  ENTITLEMENTS_HOST: {{ .Values.entitlements.serverUrl | quote }}
  SERVER_BASE_PATH: {{ .Values.basePath | quote }}
