apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentdf-abacus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: opentdf
      app.kubernetes.io/name: abacus
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: opentdf
        app.kubernetes.io/name: abacus
    spec:
      serviceAccountName: opentdf-abacus
      containers:
        - name: abacus
          envFrom:
            - configMapRef:
                name: opentdf-abacus-cm
          image: opentdf/abacus
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
