apiVersion: v1
kind: Service
metadata:
  name: {{ include "abacus.fullname" . }}
  labels:
    {{- include "abacus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
    - port: {{ int .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: opentdf
    app.kubernetes.io/name: abacus
