apiVersion: v1
kind: Service
metadata:
  name: opentdf-abacus
  labels:
    app.kubernetes.io/instance: opentdf
    app.kubernetes.io/name: abacus
spec:
  type: {{ .Values.service.type | quote }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: opentdf
    app.kubernetes.io/name: abacus
